name: mtex
description: MTEX — Hurda, çelik ve emtia piyasası
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.2.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon_bg.png"
  adaptive_icon_foreground: "assets/icon_fg.png"

flutter_native_splash:
  color: "#0E1220"
  image: assets/logo.png
  branding: assets/branding.png
  branding_mode: bottom
  android_12:
    color: "#0E1220"
    image: assets/logo.png
    branding: assets/branding.png
